# Generated by Django 2.1.5 on 2019-01-14 03:20

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('frontface', models.TextField()),
                ('backface', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2019, 1, 14, 3, 20, 49, 985884, tzinfo=utc))),
                ('activated', models.BooleanField(blank=True, null=True)),
                ('know_level', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
