# Generated by Django 2.1.5 on 2019-01-14 05:14

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='owner',
            field=models.ForeignKey(default=None, on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 14, 5, 14, 55, 644991, tzinfo=utc)),
        ),
    ]
