# Generated by Django 2.1.5 on 2019-01-18 13:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_auto_20190113_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 18, 13, 40, 39, 461372, tzinfo=utc)),
        ),
    ]
