# Generated by Django 2.1.5 on 2019-01-23 04:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0005_auto_20190119_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
